name: CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

jobs:
  build:

    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack: ['2.7.3']
        ghc: ['8.10.7']

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Setup Haskell Stack
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}

    - name: Build and run tests
      uses: actions/checkout@v2
      run: |
        stack test
